// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConfigItem 表示 .obsidian 下可同步的配置项。
 */
export class ConfigItem {
    "path": string;
    "name": string;
    "isDir": boolean;

    /** Creates a new ConfigItem instance. */
    constructor($$source: Partial<ConfigItem> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigItem($$parsedSource as Partial<ConfigItem>);
    }
}

/**
 * VaultInfo 表示扫描发现的 Obsidian vault。
 */
export class VaultInfo {
    "path": string;
    "name": string;

    /** Creates a new VaultInfo instance. */
    constructor($$source: Partial<VaultInfo> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): VaultInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VaultInfo($$parsedSource as Partial<VaultInfo>);
    }
}
