// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * VaultInfo 表示扫描发现的 Obsidian vault。
 */
export class VaultInfo {
    /**
     * Creates a new VaultInfo instance.
     * @param {Partial<VaultInfo>} [$$source = {}] - The source object to create the VaultInfo.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VaultInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VaultInfo(/** @type {Partial<VaultInfo>} */($$parsedSource));
    }
}
