// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * VaultService 向前端暴露 vault 扫描接口。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BuildSyncPlan 根据主库配置和用户选择生成覆盖同步计划，不修改文件。
 */
export function BuildSyncPlan(req: $models.SyncRequest): $CancellablePromise<$models.SyncPlan> {
    return $Call.ByID(3225252696, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListConfigItems 列出 vault 的 .obsidian 下可选择同步的配置项。
 */
export function ListConfigItems(vaultPath: string): $CancellablePromise<$models.ConfigItem[]> {
    return $Call.ByID(3677850622, vaultPath).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * OpenVaultConfigDir 使用系统文件管理器打开 vault 的 .obsidian 配置目录。
 */
export function OpenVaultConfigDir(vaultPath: string): $CancellablePromise<void> {
    return $Call.ByID(132513533, vaultPath);
}

/**
 * ScanVaults 扫描 root 并返回包含 .obsidian/ 的目录。
 */
export function ScanVaults(root: string): $CancellablePromise<$models.VaultInfo[]> {
    return $Call.ByID(4174715004, root).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SyncPlan.createFrom;
const $$createType1 = $models.ConfigItem.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.VaultInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
